//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MpgWebService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MpgWebService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOC.
        /// </summary>
        internal static string CMD_BLOCKED {
            get {
                return ResourceManager.GetString("CMD_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRLT.
        /// </summary>
        internal static string CMD_DONE {
            get {
                return ResourceManager.GetString("CMD_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRLI.
        /// </summary>
        internal static string CMD_ERROR {
            get {
                return ResourceManager.GetString("CMD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRLQ.
        /// </summary>
        internal static string CMD_QC {
            get {
                return ResourceManager.GetString("CMD_QC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELB.
        /// </summary>
        internal static string CMD_SEND {
            get {
                return ResourceManager.GetString("CMD_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRLS.
        /// </summary>
        internal static string CMD_STARTED {
            get {
                return ResourceManager.GetString("CMD_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 261.
        /// </summary>
        internal static string CONSUMPTION_TYPE {
            get {
                return ResourceManager.GetString("CONSUMPTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string MAXIMUM_DOSAGE_TIME {
            get {
                return ResourceManager.GetString("MAXIMUM_DOSAGE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        internal static string PLANT {
            get {
                return ResourceManager.GetString("PLANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101.
        /// </summary>
        internal static string RECEIPT_TYPE {
            get {
                return ResourceManager.GetString("RECEIPT_TYPE", resourceCulture);
            }
        }
    }
}
