//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BLOC")]
        public string CMD_BLOCK {
            get {
                return ((string)(this["CMD_BLOCK"]));
            }
            set {
                this["CMD_BLOCK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ELB")]
        public string CMD_ELB {
            get {
                return ((string)(this["CMD_ELB"]));
            }
            set {
                this["CMD_ELB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PRLI")]
        public string CMD_PRLI {
            get {
                return ((string)(this["CMD_PRLI"]));
            }
            set {
                this["CMD_PRLI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PRLS")]
        public string CMD_PRLS {
            get {
                return ((string)(this["CMD_PRLS"]));
            }
            set {
                this["CMD_PRLS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PLRT")]
        public string CMD_PLRT {
            get {
                return ((string)(this["CMD_PLRT"]));
            }
            set {
                this["CMD_PLRT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string MaximumDosageTime {
            get {
                return ((string)(this["MaximumDosageTime"]));
            }
            set {
                this["MaximumDosageTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MPGINTERFACE")]
        public string MES_Database {
            get {
                return ((string)(this["MES_Database"]));
            }
            set {
                this["MES_Database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kober2019!@#")]
        public string MES_Pass {
            get {
                return ((string)(this["MES_Pass"]));
            }
            set {
                this["MES_Pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.10.30")]
        public string MES_Production {
            get {
                return ((string)(this["MES_Production"]));
            }
            set {
                this["MES_Production"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kober.1234")]
        public string MES_Production_Pass {
            get {
                return ((string)(this["MES_Production_Pass"]));
            }
            set {
                this["MES_Production_Pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string MES_Production_User {
            get {
                return ((string)(this["MES_Production_User"]));
            }
            set {
                this["MES_Production_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.10.14")]
        public string MES_Server {
            get {
                return ((string)(this["MES_Server"]));
            }
            set {
                this["MES_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MPG")]
        public string MES_User {
            get {
                return ((string)(this["MES_User"]));
            }
            set {
                this["MES_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MPG")]
        public string MPG_Database {
            get {
                return ((string)(this["MPG_Database"]));
            }
            set {
                this["MPG_Database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kober2022!")]
        public string MPG_Pass {
            get {
                return ((string)(this["MPG_Pass"]));
            }
            set {
                this["MPG_Pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.10.26")]
        public string MPG_Server {
            get {
                return ((string)(this["MPG_Server"]));
            }
            set {
                this["MPG_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string MPG_User {
            get {
                return ((string)(this["MPG_User"]));
            }
            set {
                this["MPG_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Local.sqlite")]
        public string Path_Sqlite {
            get {
                return ((string)(this["Path_Sqlite"]));
            }
            set {
                this["Path_Sqlite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MES_2022")]
        public string SAP_Pass {
            get {
                return ((string)(this["SAP_Pass"]));
            }
            set {
                this["SAP_Pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://DEZV-ECC.kober.ro:8000/sap/bc/srt/rfc/sap/z_mpg/200/z_mpg/z_mpg")]
        public string SAP_Server {
            get {
                return ((string)(this["SAP_Server"]));
            }
            set {
                this["SAP_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USERMES")]
        public string SAP_User {
            get {
                return ((string)(this["SAP_User"]));
            }
            set {
                this["SAP_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string Docker_Server {
            get {
                return ((string)(this["Docker_Server"]));
            }
            set {
                this["Docker_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string Docker_User {
            get {
                return ((string)(this["Docker_User"]));
            }
            set {
                this["Docker_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kober2020!")]
        public string Docker_Pass {
            get {
                return ((string)(this["Docker_Pass"]));
            }
            set {
                this["Docker_Pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MPG")]
        public string Docker_Database {
            get {
                return ((string)(this["Docker_Database"]));
            }
            set {
                this["Docker_Database"] = value;
            }
        }
    }
}
