//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPG_Interface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPG_Interface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOC.
        /// </summary>
        internal static string CMD_BLOCK {
            get {
                return ResourceManager.GetString("CMD_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELB.
        /// </summary>
        internal static string CMD_ELB {
            get {
                return ResourceManager.GetString("CMD_ELB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRLI.
        /// </summary>
        internal static string CMD_PRLI {
            get {
                return ResourceManager.GetString("CMD_PRLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRLS.
        /// </summary>
        internal static string CMD_PRLS {
            get {
                return ResourceManager.GetString("CMD_PRLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRLT.
        /// </summary>
        internal static string CMD_PRLT {
            get {
                return ResourceManager.GetString("CMD_PRLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 261.
        /// </summary>
        internal static string Consumption_Type {
            get {
                return ResourceManager.GetString("Consumption_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101.
        /// </summary>
        internal static string Goods_Receipt_Type {
            get {
                return ResourceManager.GetString("Goods_Receipt_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPGINTERFACE.
        /// </summary>
        internal static string MES_Database {
            get {
                return ResourceManager.GetString("MES_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kober2019!@#.
        /// </summary>
        internal static string MES_Pass {
            get {
                return ResourceManager.GetString("MES_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192.168.10.14.
        /// </summary>
        internal static string MES_Server {
            get {
                return ResourceManager.GetString("MES_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPG.
        /// </summary>
        internal static string MES_User {
            get {
                return ResourceManager.GetString("MES_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:\Work\C#\Local.sqlite.
        /// </summary>
        internal static string Path_Sqlite {
            get {
                return ResourceManager.GetString("Path_Sqlite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MES_2022.
        /// </summary>
        internal static string SAP_Pass {
            get {
                return ResourceManager.GetString("SAP_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://DEZV-ECC.kober.ro:8000/sap/bc/srt/rfc/sap/z_mpg/200/z_mpg/z_mpg.
        /// </summary>
        internal static string SAP_Server {
            get {
                return ResourceManager.GetString("SAP_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USERMES.
        /// </summary>
        internal static string SAP_User {
            get {
                return ResourceManager.GetString("SAP_User", resourceCulture);
            }
        }
    }
}
